### ISSUE TITLE
Tests to cover out-of-bounds queries for array-based implementations

### ISSUE THREAD

**Issue by carrutstick** [carrutstick/cuml_map#1]
We need tests written to cover `get_single` and `get_cuml` calls to `FenwickTree` and `ExtensibleFenwickTree` where the keys are outside the existing bounds of the structures. For instance:

```rust
let mut t = FenwickTree::with_capacity(5);
t.insert(3, 2);
assert_eq!(t.get_single(6), 0);
```

**Comment by Henning-K** [comment]
I'd love to work on this over the course of this weekend.
